# SQL Server - SQL Server Authentication
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Respetar exactamente los nombres de SQL Server
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# CORS (frontend)
app.cors.allowed-origins=http://localhost:5173

# Mostrar el mensaje real del Error en la respuesta
server.error.include-message=always
server.error.include-binding-errors=always